"""4

Revision ID: 0766b87bdb66
Revises: dc8bf64e6752
Create Date: 2022-10-31 01:27:27.661687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0766b87bdb66'
down_revision = 'dc8bf64e6752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
