"""6

Revision ID: 307460bf4e24
Revises: 3f928cdfe77d
Create Date: 2022-10-31 01:36:17.215007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307460bf4e24'
down_revision = '3f928cdfe77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
