"""5

Revision ID: 3f928cdfe77d
Revises: 0766b87bdb66
Create Date: 2022-10-31 01:36:07.939724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f928cdfe77d'
down_revision = '0766b87bdb66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
