"""8

Revision ID: 49d09000b6fd
Revises: a421541f1837
Create Date: 2022-10-31 01:51:51.502795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d09000b6fd'
down_revision = 'a421541f1837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
