"""9

Revision ID: d9e7258fdf11
Revises: 49d09000b6fd
Create Date: 2022-10-31 01:51:58.193198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e7258fdf11'
down_revision = '49d09000b6fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
