"""4

Revision ID: dc8bf64e6752
Revises: ab2f521c0de9
Create Date: 2022-10-31 01:26:53.033496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc8bf64e6752'
down_revision = 'ab2f521c0de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
